[tool.poetry]
name = "invest-tracker-backend"
version = "1.0.0"
description = "Backend for investment tracking app"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
